# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS FileCheck llvm-PerfectShuffle count not UnicodeNameMappingGenerator yaml-bench split-file llvm-test-mustache-spec lli-child-target LLVMIREmbUtils LLVMMIREmbUtils llvm-jitlink-executor obj2yaml yaml2obj)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target FileCheck
add_executable(FileCheck IMPORTED)

# Create imported target llvm-PerfectShuffle
add_executable(llvm-PerfectShuffle IMPORTED)

# Create imported target count
add_executable(count IMPORTED)

# Create imported target not
add_executable(not IMPORTED)

# Create imported target UnicodeNameMappingGenerator
add_executable(UnicodeNameMappingGenerator IMPORTED)

# Create imported target yaml-bench
add_executable(yaml-bench IMPORTED)

# Create imported target split-file
add_executable(split-file IMPORTED)

# Create imported target llvm-test-mustache-spec
add_executable(llvm-test-mustache-spec IMPORTED)

# Create imported target lli-child-target
add_executable(lli-child-target IMPORTED)

# Create imported target LLVMIREmbUtils
add_library(LLVMIREmbUtils STATIC IMPORTED)

set_target_properties(LLVMIREmbUtils PROPERTIES
  INTERFACE_LINK_LIBRARIES "LLVMAnalysis;LLVMCore;LLVMSupport;LLVMIRReader;LLVMCodeGen;LLVMMIRParser;LLVMMC;LLVMTarget;LLVMAArch64AsmParser;LLVMX86AsmParser;LLVMAArch64CodeGen;LLVMX86CodeGen;LLVMAArch64Desc;LLVMX86Desc;LLVMAArch64Info;LLVMX86Info;LLVMTargetParser;LLVMAnalysis;LLVMCore;LLVMSupport"
)

# Create imported target LLVMMIREmbUtils
add_library(LLVMMIREmbUtils STATIC IMPORTED)

set_target_properties(LLVMMIREmbUtils PROPERTIES
  INTERFACE_LINK_LIBRARIES "LLVMAnalysis;LLVMCore;LLVMSupport;LLVMIRReader;LLVMCodeGen;LLVMMIRParser;LLVMMC;LLVMTarget;LLVMAArch64AsmParser;LLVMX86AsmParser;LLVMAArch64CodeGen;LLVMX86CodeGen;LLVMAArch64Desc;LLVMX86Desc;LLVMAArch64Info;LLVMX86Info;LLVMTargetParser;LLVMCodeGen;LLVMTarget"
)

# Create imported target llvm-jitlink-executor
add_executable(llvm-jitlink-executor IMPORTED)

# Create imported target obj2yaml
add_executable(obj2yaml IMPORTED)

# Create imported target yaml2obj
add_executable(yaml2obj IMPORTED)

# Import target "FileCheck" for configuration "Release"
set_property(TARGET FileCheck APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(FileCheck PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/FileCheck.exe"
  )

# Import target "llvm-PerfectShuffle" for configuration "Release"
set_property(TARGET llvm-PerfectShuffle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(llvm-PerfectShuffle PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/llvm-PerfectShuffle.exe"
  )

# Import target "count" for configuration "Release"
set_property(TARGET count APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(count PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/count.exe"
  )

# Import target "not" for configuration "Release"
set_property(TARGET not APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(not PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/not.exe"
  )

# Import target "UnicodeNameMappingGenerator" for configuration "Release"
set_property(TARGET UnicodeNameMappingGenerator APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(UnicodeNameMappingGenerator PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/UnicodeNameMappingGenerator.exe"
  )

# Import target "yaml-bench" for configuration "Release"
set_property(TARGET yaml-bench APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(yaml-bench PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/yaml-bench.exe"
  )

# Import target "split-file" for configuration "Release"
set_property(TARGET split-file APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(split-file PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/split-file.exe"
  )

# Import target "llvm-test-mustache-spec" for configuration "Release"
set_property(TARGET llvm-test-mustache-spec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(llvm-test-mustache-spec PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/llvm-test-mustache-spec.exe"
  )

# Import target "lli-child-target" for configuration "Release"
set_property(TARGET lli-child-target APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(lli-child-target PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/lli-child-target.exe"
  )

# Import target "LLVMIREmbUtils" for configuration "Release"
set_property(TARGET LLVMIREmbUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(LLVMIREmbUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/lib/LLVMIREmbUtils.lib"
  )

# Import target "LLVMMIREmbUtils" for configuration "Release"
set_property(TARGET LLVMMIREmbUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(LLVMMIREmbUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/lib/LLVMMIREmbUtils.lib"
  )

# Import target "llvm-jitlink-executor" for configuration "Release"
set_property(TARGET llvm-jitlink-executor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(llvm-jitlink-executor PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/llvm-jitlink-executor.exe"
  )

# Import target "obj2yaml" for configuration "Release"
set_property(TARGET obj2yaml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(obj2yaml PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/obj2yaml.exe"
  )

# Import target "yaml2obj" for configuration "Release"
set_property(TARGET yaml2obj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(yaml2obj PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/Downloads/Vyft_product/Maratinelang/maratinec/bin/yaml2obj.exe"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "LLVMAnalysis" "LLVMCore" "LLVMSupport" "LLVMIRReader" "LLVMCodeGen" "LLVMMIRParser" "LLVMMC" "LLVMTarget" "LLVMAArch64AsmParser" "LLVMX86AsmParser" "LLVMAArch64CodeGen" "LLVMX86CodeGen" "LLVMAArch64Desc" "LLVMX86Desc" "LLVMAArch64Info" "LLVMX86Info" "LLVMTargetParser" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
