; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=aarch64 -passes=aarch64-codegenprepare -S %s | FileCheck %s
; RUN: opt -mtriple=aarch64 -passes=aarch64-codegenprepare -aarch64-widen-cross-block-bool-vec=false -S %s | FileCheck %s --check-prefix=DISABLE

;; IR-level tests for AArch64CodeGenPrepare's widening of cross-block
;; <N x i1> chains. Each test exercises one rewriting facet so failures
;; pinpoint a specific behavior.

;-----------------------------------------------------------------------
; Trigger gating
;-----------------------------------------------------------------------

;; A chain that has no cross-block use is left alone.
define <4 x i32> @no_crossblock(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, <4 x i32> %d) {
; CHECK-LABEL: define <4 x i32> @no_crossblock(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[C:%.*]], <4 x i32> [[D:%.*]]) {
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq <4 x i32> [[C]], [[D]]
; CHECK-NEXT:    [[AND:%.*]] = and <4 x i1> [[CMP1]], [[CMP2]]
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[AND]], <4 x i32> [[A]], <4 x i32> [[B]]
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
; DISABLE-LABEL: define <4 x i32> @no_crossblock(
; DISABLE-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[C:%.*]], <4 x i32> [[D:%.*]]) {
; DISABLE-NEXT:    [[CMP1:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; DISABLE-NEXT:    [[CMP2:%.*]] = icmp eq <4 x i32> [[C]], [[D]]
; DISABLE-NEXT:    [[AND:%.*]] = and <4 x i1> [[CMP1]], [[CMP2]]
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[AND]], <4 x i32> [[A]], <4 x i32> [[B]]
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
;
  %cmp1 = icmp eq <4 x i32> %a, %b
  %cmp2 = icmp eq <4 x i32> %c, %d
  %and = and <4 x i1> %cmp1, %cmp2
  %sel = select <4 x i1> %and, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

;; A chain with cross-block uses but no joining op (just a cmp + extracts in
;; another block) is degenerate -- widening + re-narrowing buys nothing.
;; Pass must skip.
define void @bare_cmp_crossblock_extract(<2 x i64> %v, ptr %dst) {
; CHECK-LABEL: define void @bare_cmp_crossblock_extract(
; CHECK-SAME: <2 x i64> [[V:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VEC_CMP:%.*]] = icmp ult <2 x i64> [[V]], splat (i64 15)
; CHECK-NEXT:    [[C0:%.*]] = extractelement <2 x i1> [[VEC_CMP]], i64 0
; CHECK-NEXT:    br i1 [[C0]], label %[[STORE:.*]], label %[[CONT:.*]]
; CHECK:       [[STORE]]:
; CHECK-NEXT:    [[C1:%.*]] = extractelement <2 x i1> [[VEC_CMP]], i64 1
; CHECK-NEXT:    store i32 1, ptr [[DST]], align 4
; CHECK-NEXT:    br label %[[CONT]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    ret void
;
; DISABLE-LABEL: define void @bare_cmp_crossblock_extract(
; DISABLE-SAME: <2 x i64> [[V:%.*]], ptr [[DST:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[VEC_CMP:%.*]] = icmp ult <2 x i64> [[V]], splat (i64 15)
; DISABLE-NEXT:    [[C0:%.*]] = extractelement <2 x i1> [[VEC_CMP]], i64 0
; DISABLE-NEXT:    br i1 [[C0]], label %[[STORE:.*]], label %[[CONT:.*]]
; DISABLE:       [[STORE]]:
; DISABLE-NEXT:    [[C1:%.*]] = extractelement <2 x i1> [[VEC_CMP]], i64 1
; DISABLE-NEXT:    store i32 1, ptr [[DST]], align 4
; DISABLE-NEXT:    br label %[[CONT]]
; DISABLE:       [[CONT]]:
; DISABLE-NEXT:    ret void
;
entry:
  %vec.cmp = icmp ult <2 x i64> %v, <i64 15, i64 15>
  %c0 = extractelement <2 x i1> %vec.cmp, i64 0
  br i1 %c0, label %store, label %cont
store:
  %c1 = extractelement <2 x i1> %vec.cmp, i64 1
  store i32 1, ptr %dst, align 4
  br label %cont
cont:
  ret void
}

;; Chain that would widen above 128 bits is skipped: <16 x i64> = 1024 bits.
define void @too_wide_cap(ptr %p, <16 x i64> %a, <16 x i64> %b, <16 x i64> %c) {
; CHECK-LABEL: define void @too_wide_cap(
; CHECK-SAME: ptr [[P:%.*]], <16 x i64> [[A:%.*]], <16 x i64> [[B:%.*]], <16 x i64> [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult <16 x i64> [[A]], [[B]]
; CHECK-NEXT:    [[CMP2:%.*]] = icmp ult <16 x i64> [[A]], [[C]]
; CHECK-NEXT:    br label %[[USE:.*]]
; CHECK:       [[USE]]:
; CHECK-NEXT:    [[AND:%.*]] = and <16 x i1> [[CMP1]], [[CMP2]]
; CHECK-NEXT:    store <16 x i1> [[AND]], ptr [[P]], align 2
; CHECK-NEXT:    ret void
;
; DISABLE-LABEL: define void @too_wide_cap(
; DISABLE-SAME: ptr [[P:%.*]], <16 x i64> [[A:%.*]], <16 x i64> [[B:%.*]], <16 x i64> [[C:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP1:%.*]] = icmp ult <16 x i64> [[A]], [[B]]
; DISABLE-NEXT:    [[CMP2:%.*]] = icmp ult <16 x i64> [[A]], [[C]]
; DISABLE-NEXT:    br label %[[USE:.*]]
; DISABLE:       [[USE]]:
; DISABLE-NEXT:    [[AND:%.*]] = and <16 x i1> [[CMP1]], [[CMP2]]
; DISABLE-NEXT:    store <16 x i1> [[AND]], ptr [[P]], align 2
; DISABLE-NEXT:    ret void
;
entry:
  %cmp1 = icmp ult <16 x i64> %a, %b
  %cmp2 = icmp ult <16 x i64> %a, %c
  br label %use
use:
  %and = and <16 x i1> %cmp1, %cmp2
  store <16 x i1> %and, ptr %p
  ret void
}

;-----------------------------------------------------------------------
; Cross-block PHI chain (the canonical motivating case)
;-----------------------------------------------------------------------

;; A loop-carried <4 x i1> PHI accumulating an AND of compare results.
;; The chain (PHI + compares + AND) is rewritten on <4 x i32>.
define <4 x i32> @phi_loop(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, i32 %n) {
; CHECK-LABEL: define <4 x i32> @phi_loop(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[C:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP_INIT:%.*]] = icmp slt <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[CMP_INIT_WIDE:%.*]] = sext <4 x i1> [[CMP_INIT]] to <4 x i32>
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MASK_WIDE:%.*]] = phi <4 x i32> [ [[CMP_INIT_WIDE]], %[[ENTRY]] ], [ [[MASK_NEXT_WIDE:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MASK_NARROW:%.*]] = icmp slt <4 x i32> [[MASK_WIDE]], zeroinitializer
; CHECK-NEXT:    [[CMP_LOOP:%.*]] = icmp sgt <4 x i32> [[B]], [[C]]
; CHECK-NEXT:    [[CMP_LOOP_WIDE:%.*]] = sext <4 x i1> [[CMP_LOOP]] to <4 x i32>
; CHECK-NEXT:    [[MASK_NEXT_WIDE]] = and <4 x i32> [[MASK_WIDE]], [[CMP_LOOP_WIDE]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[MASK_NARROW]], <4 x i32> [[A]], <4 x i32> [[C]]
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
; DISABLE-LABEL: define <4 x i32> @phi_loop(
; DISABLE-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[C:%.*]], i32 [[N:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*]]:
; DISABLE-NEXT:    [[CMP_INIT:%.*]] = icmp slt <4 x i32> [[A]], [[B]]
; DISABLE-NEXT:    br label %[[LOOP:.*]]
; DISABLE:       [[LOOP]]:
; DISABLE-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; DISABLE-NEXT:    [[MASK:%.*]] = phi <4 x i1> [ [[CMP_INIT]], %[[ENTRY]] ], [ [[MASK_NEXT:%.*]], %[[LOOP]] ]
; DISABLE-NEXT:    [[CMP_LOOP:%.*]] = icmp sgt <4 x i32> [[B]], [[C]]
; DISABLE-NEXT:    [[MASK_NEXT]] = and <4 x i1> [[MASK]], [[CMP_LOOP]]
; DISABLE-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; DISABLE-NEXT:    [[COND:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; DISABLE-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; DISABLE:       [[EXIT]]:
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[MASK]], <4 x i32> [[A]], <4 x i32> [[C]]
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
;
entry:
  %cmp.init = icmp slt <4 x i32> %a, %b
  br label %loop
loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %mask = phi <4 x i1> [ %cmp.init, %entry ], [ %mask.next, %loop ]
  %cmp.loop = icmp sgt <4 x i32> %b, %c
  %mask.next = and <4 x i1> %mask, %cmp.loop
  %i.next = add i32 %i, 1
  %cond = icmp slt i32 %i.next, %n
  br i1 %cond, label %loop, label %exit
exit:
  %sel = select <4 x i1> %mask, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

;-----------------------------------------------------------------------
; Mixed-source-width chain: pick wider rule
;-----------------------------------------------------------------------

;; cmp_v4i32 + cmp_v4i16 join at an `and` whose result is consumed in
;; another block. The pass must pick v4i32 (the wider) and sext-widen the
;; v4i16 cmp.
define <4 x i32> @mixed_widths_pick_wider(<4 x i32> %a32, <4 x i32> %b32,
; CHECK-LABEL: define <4 x i32> @mixed_widths_pick_wider(
; CHECK-SAME: <4 x i32> [[A32:%.*]], <4 x i32> [[B32:%.*]], <4 x i16> [[A16:%.*]], <4 x i16> [[B16:%.*]], <4 x i32> [[X:%.*]], <4 x i32> [[Y:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP32:%.*]] = icmp eq <4 x i32> [[A32]], [[B32]]
; CHECK-NEXT:    [[CMP32_WIDE:%.*]] = sext <4 x i1> [[CMP32]] to <4 x i32>
; CHECK-NEXT:    [[CMP16:%.*]] = icmp eq <4 x i16> [[A16]], [[B16]]
; CHECK-NEXT:    [[CMP16_WIDE:%.*]] = sext <4 x i1> [[CMP16]] to <4 x i32>
; CHECK-NEXT:    [[AND_WIDE:%.*]] = and <4 x i32> [[CMP32_WIDE]], [[CMP16_WIDE]]
; CHECK-NEXT:    [[AND_NARROW:%.*]] = icmp slt <4 x i32> [[AND_WIDE]], zeroinitializer
; CHECK-NEXT:    br i1 [[C]], label %[[USE:.*]], label %[[OTHER:.*]]
; CHECK:       [[USE]]:
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[AND_NARROW]], <4 x i32> [[X]], <4 x i32> [[Y]]
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    ret <4 x i32> [[X]]
;
; DISABLE-LABEL: define <4 x i32> @mixed_widths_pick_wider(
; DISABLE-SAME: <4 x i32> [[A32:%.*]], <4 x i32> [[B32:%.*]], <4 x i16> [[A16:%.*]], <4 x i16> [[B16:%.*]], <4 x i32> [[X:%.*]], <4 x i32> [[Y:%.*]], i1 [[C:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP32:%.*]] = icmp eq <4 x i32> [[A32]], [[B32]]
; DISABLE-NEXT:    [[CMP16:%.*]] = icmp eq <4 x i16> [[A16]], [[B16]]
; DISABLE-NEXT:    [[AND:%.*]] = and <4 x i1> [[CMP32]], [[CMP16]]
; DISABLE-NEXT:    br i1 [[C]], label %[[USE:.*]], label %[[OTHER:.*]]
; DISABLE:       [[USE]]:
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[AND]], <4 x i32> [[X]], <4 x i32> [[Y]]
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
; DISABLE:       [[OTHER]]:
; DISABLE-NEXT:    ret <4 x i32> [[X]]
;
  <4 x i16> %a16, <4 x i16> %b16,
  <4 x i32> %x, <4 x i32> %y, i1 %c) {
entry:
  %cmp32 = icmp eq <4 x i32> %a32, %b32
  %cmp16 = icmp eq <4 x i16> %a16, %b16
  %and = and <4 x i1> %cmp32, %cmp16
  br i1 %c, label %use, label %other
use:
  %sel = select <4 x i1> %and, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
other:
  ret <4 x i32> %x
}

;-----------------------------------------------------------------------
; fcmp predicates that produce ordered/unordered results
;-----------------------------------------------------------------------

;; fcmp uno (unordered) chained with a phi -- still sext-widenable.
define <4 x float> @fcmp_uno_phi(<4 x float> %a, <4 x float> %b, <4 x float> %x, i1 %c) {
; CHECK-LABEL: define <4 x float> @fcmp_uno_phi(
; CHECK-SAME: <4 x float> [[A:%.*]], <4 x float> [[B:%.*]], <4 x float> [[X:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp uno <4 x float> [[A]], [[B]]
; CHECK-NEXT:    [[CMP1_WIDE:%.*]] = sext <4 x i1> [[CMP1]] to <4 x i32>
; CHECK-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; CHECK:       [[L]]:
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ord <4 x float> [[A]], [[B]]
; CHECK-NEXT:    [[CMP2_WIDE:%.*]] = sext <4 x i1> [[CMP2]] to <4 x i32>
; CHECK-NEXT:    br label %[[J:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[M_WIDE:%.*]] = phi <4 x i32> [ [[CMP2_WIDE]], %[[L]] ], [ [[CMP1_WIDE]], %[[R]] ]
; CHECK-NEXT:    [[M_NARROW:%.*]] = icmp slt <4 x i32> [[M_WIDE]], zeroinitializer
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M_NARROW]], <4 x float> [[A]], <4 x float> [[X]]
; CHECK-NEXT:    ret <4 x float> [[SEL]]
;
; DISABLE-LABEL: define <4 x float> @fcmp_uno_phi(
; DISABLE-SAME: <4 x float> [[A:%.*]], <4 x float> [[B:%.*]], <4 x float> [[X:%.*]], i1 [[C:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP1:%.*]] = fcmp uno <4 x float> [[A]], [[B]]
; DISABLE-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; DISABLE:       [[L]]:
; DISABLE-NEXT:    [[CMP2:%.*]] = fcmp ord <4 x float> [[A]], [[B]]
; DISABLE-NEXT:    br label %[[J:.*]]
; DISABLE:       [[R]]:
; DISABLE-NEXT:    br label %[[J]]
; DISABLE:       [[J]]:
; DISABLE-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP2]], %[[L]] ], [ [[CMP1]], %[[R]] ]
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x float> [[A]], <4 x float> [[X]]
; DISABLE-NEXT:    ret <4 x float> [[SEL]]
;
entry:
  %cmp1 = fcmp uno <4 x float> %a, %b
  br i1 %c, label %l, label %r
l:
  %cmp2 = fcmp ord <4 x float> %a, %b
  br label %j
r:
  br label %j
j:
  %m = phi <4 x i1> [ %cmp2, %l ], [ %cmp1, %r ]
  %sel = select <4 x i1> %m, <4 x float> %a, <4 x float> %x
  ret <4 x float> %sel
}

;-----------------------------------------------------------------------
; Pointer compare as producer
;-----------------------------------------------------------------------

;; icmp on pointer vectors: source element width matches the pointer width
;; (i64 on aarch64). Chain widens to v4i64 -- 256 bits. This exceeds the
;; profitability cap of 128 bits and must be skipped.
define <4 x i32> @ptr_cmp_phi_too_wide(<4 x ptr> %a, <4 x ptr> %b, <4 x i32> %x, i1 %c) {
; CHECK-LABEL: define <4 x i32> @ptr_cmp_phi_too_wide(
; CHECK-SAME: <4 x ptr> [[A:%.*]], <4 x ptr> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq <4 x ptr> [[A]], [[B]]
; CHECK-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; CHECK:       [[L]]:
; CHECK-NEXT:    [[CMP2:%.*]] = icmp ne <4 x ptr> [[A]], [[B]]
; CHECK-NEXT:    br label %[[J:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP2]], %[[L]] ], [ [[CMP1]], %[[R]] ]
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
; DISABLE-LABEL: define <4 x i32> @ptr_cmp_phi_too_wide(
; DISABLE-SAME: <4 x ptr> [[A:%.*]], <4 x ptr> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP1:%.*]] = icmp eq <4 x ptr> [[A]], [[B]]
; DISABLE-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; DISABLE:       [[L]]:
; DISABLE-NEXT:    [[CMP2:%.*]] = icmp ne <4 x ptr> [[A]], [[B]]
; DISABLE-NEXT:    br label %[[J:.*]]
; DISABLE:       [[R]]:
; DISABLE-NEXT:    br label %[[J]]
; DISABLE:       [[J]]:
; DISABLE-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP2]], %[[L]] ], [ [[CMP1]], %[[R]] ]
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
;
entry:
  %cmp1 = icmp eq <4 x ptr> %a, %b
  br i1 %c, label %l, label %r
l:
  %cmp2 = icmp ne <4 x ptr> %a, %b
  br label %j
r:
  br label %j
j:
  %m = phi <4 x i1> [ %cmp2, %l ], [ %cmp1, %r ]
  %sel = select <4 x i1> %m, <4 x i32> %x, <4 x i32> zeroinitializer
  ret <4 x i32> %sel
}

;-----------------------------------------------------------------------
; Length-changing shufflevector across a phi
;-----------------------------------------------------------------------

;; A shufflevector that produces a different element count breaks chain
;; connectivity at the NumElts boundary; each NumElts gets its own chain.
;; The pass must not pull values of different element counts into one
;; rewrite.
define <4 x i32> @length_changing_shuffle(<8 x float> %a, <8 x float> %b,
; CHECK-LABEL: define <4 x i32> @length_changing_shuffle(
; CHECK-SAME: <8 x float> [[A:%.*]], <8 x float> [[B:%.*]], <4 x i32> [[X:%.*]], <4 x i32> [[Y:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP8:%.*]] = fcmp ole <8 x float> [[A]], [[B]]
; CHECK-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; CHECK:       [[L]]:
; CHECK-NEXT:    [[SHUF:%.*]] = shufflevector <8 x i1> [[CMP8]], <8 x i1> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    br label %[[J:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[SHUF]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> [[Y]]
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
; DISABLE-LABEL: define <4 x i32> @length_changing_shuffle(
; DISABLE-SAME: <8 x float> [[A:%.*]], <8 x float> [[B:%.*]], <4 x i32> [[X:%.*]], <4 x i32> [[Y:%.*]], i1 [[C:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP8:%.*]] = fcmp ole <8 x float> [[A]], [[B]]
; DISABLE-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; DISABLE:       [[L]]:
; DISABLE-NEXT:    [[SHUF:%.*]] = shufflevector <8 x i1> [[CMP8]], <8 x i1> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; DISABLE-NEXT:    br label %[[J:.*]]
; DISABLE:       [[R]]:
; DISABLE-NEXT:    br label %[[J]]
; DISABLE:       [[J]]:
; DISABLE-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[SHUF]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> [[Y]]
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
;
  <4 x i32> %x, <4 x i32> %y, i1 %c) {
entry:
  %cmp8 = fcmp ole <8 x float> %a, %b
  br i1 %c, label %l, label %r
l:
  %shuf = shufflevector <8 x i1> %cmp8, <8 x i1> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  br label %j
r:
  br label %j
j:
  %m = phi <4 x i1> [ %shuf, %l ], [ zeroinitializer, %r ]
  %sel = select <4 x i1> %m, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

;-----------------------------------------------------------------------
; Constant <N x i1> operands inside the chain
;-----------------------------------------------------------------------

;; A constant <4 x i1> in the and/or chain gets a sext to the wide type.
define <4 x i32> @constant_in_chain(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x, i1 %c) {
; CHECK-LABEL: define <4 x i32> @constant_in_chain(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[CMP_WIDE:%.*]] = sext <4 x i1> [[CMP]] to <4 x i32>
; CHECK-NEXT:    [[MASKED_WIDE:%.*]] = and <4 x i32> [[CMP_WIDE]], <i32 -1, i32 0, i32 -1, i32 0>
; CHECK-NEXT:    [[MASKED_NARROW:%.*]] = icmp slt <4 x i32> [[MASKED_WIDE]], zeroinitializer
; CHECK-NEXT:    br i1 [[C]], label %[[USE:.*]], label %[[OUT:.*]]
; CHECK:       [[USE]]:
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[MASKED_NARROW]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
; CHECK:       [[OUT]]:
; CHECK-NEXT:    ret <4 x i32> [[A]]
;
; DISABLE-LABEL: define <4 x i32> @constant_in_chain(
; DISABLE-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; DISABLE-NEXT:    [[MASKED:%.*]] = and <4 x i1> [[CMP]], <i1 true, i1 false, i1 true, i1 false>
; DISABLE-NEXT:    br i1 [[C]], label %[[USE:.*]], label %[[OUT:.*]]
; DISABLE:       [[USE]]:
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[MASKED]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
; DISABLE:       [[OUT]]:
; DISABLE-NEXT:    ret <4 x i32> [[A]]
;
entry:
  %cmp = icmp eq <4 x i32> %a, %b
  %masked = and <4 x i1> %cmp, <i1 true, i1 false, i1 true, i1 false>
  br i1 %c, label %use, label %out
use:
  %sel = select <4 x i1> %masked, <4 x i32> %x, <4 x i32> zeroinitializer
  ret <4 x i32> %sel
out:
  ret <4 x i32> %a
}

;-----------------------------------------------------------------------
; optnone: pass must skip
;-----------------------------------------------------------------------

;; Function attribute optnone disables the rewrite.
define <4 x i32> @optnone_skipped(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x, i1 %c) noinline optnone {
; CHECK-LABEL: define <4 x i32> @optnone_skipped(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; CHECK:       [[L]]:
; CHECK-NEXT:    br label %[[J:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
; DISABLE-LABEL: define <4 x i32> @optnone_skipped(
; DISABLE-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; DISABLE-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; DISABLE:       [[L]]:
; DISABLE-NEXT:    br label %[[J:.*]]
; DISABLE:       [[R]]:
; DISABLE-NEXT:    br label %[[J]]
; DISABLE:       [[J]]:
; DISABLE-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
;
entry:
  %cmp = icmp eq <4 x i32> %a, %b
  br i1 %c, label %l, label %r
l:
  br label %j
r:
  br label %j
j:
  %m = phi <4 x i1> [ %cmp, %l ], [ zeroinitializer, %r ]
  %sel = select <4 x i1> %m, <4 x i32> %x, <4 x i32> zeroinitializer
  ret <4 x i32> %sel
}

;-----------------------------------------------------------------------
; Streaming-mode (SME) functions are skipped
;-----------------------------------------------------------------------

;; Functions with SME streaming-mode interface go through a different
;; predicate-lowering path; the pass leaves them alone.
define <4 x i32> @sme_streaming_skipped(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x, i1 %c) "aarch64_pstate_sm_enabled" {
; CHECK-LABEL: define <4 x i32> @sme_streaming_skipped(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; CHECK:       [[L]]:
; CHECK-NEXT:    br label %[[J:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
; DISABLE-LABEL: define <4 x i32> @sme_streaming_skipped(
; DISABLE-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) #[[ATTR1:[0-9]+]] {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; DISABLE-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; DISABLE:       [[L]]:
; DISABLE-NEXT:    br label %[[J:.*]]
; DISABLE:       [[R]]:
; DISABLE-NEXT:    br label %[[J]]
; DISABLE:       [[J]]:
; DISABLE-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
;
entry:
  %cmp = icmp eq <4 x i32> %a, %b
  br i1 %c, label %l, label %r
l:
  br label %j
r:
  br label %j
j:
  %m = phi <4 x i1> [ %cmp, %l ], [ zeroinitializer, %r ]
  %sel = select <4 x i1> %m, <4 x i32> %x, <4 x i32> zeroinitializer
  ret <4 x i32> %sel
}

;-----------------------------------------------------------------------
; Multiple independent chains in one function
;-----------------------------------------------------------------------

;; Two unrelated <4 x i1> chains in the same function should both be
;; widened independently.
define void @two_independent_chains(<4 x i32> %a, <4 x i32> %b, <4 x float> %fa, <4 x float> %fb,
; CHECK-LABEL: define void @two_independent_chains(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x float> [[FA:%.*]], <4 x float> [[FB:%.*]], ptr [[P1:%.*]], ptr [[P2:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ICMP1:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[ICMP1_WIDE:%.*]] = sext <4 x i1> [[ICMP1]] to <4 x i32>
; CHECK-NEXT:    [[FCMP1:%.*]] = fcmp olt <4 x float> [[FA]], [[FB]]
; CHECK-NEXT:    [[FCMP1_WIDE:%.*]] = sext <4 x i1> [[FCMP1]] to <4 x i32>
; CHECK-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; CHECK:       [[L]]:
; CHECK-NEXT:    br label %[[J:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[IM_WIDE:%.*]] = phi <4 x i32> [ [[ICMP1_WIDE]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; CHECK-NEXT:    [[FM_WIDE:%.*]] = phi <4 x i32> [ [[FCMP1_WIDE]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; CHECK-NEXT:    [[FM_NARROW:%.*]] = icmp slt <4 x i32> [[FM_WIDE]], zeroinitializer
; CHECK-NEXT:    [[IM_NARROW:%.*]] = icmp slt <4 x i32> [[IM_WIDE]], zeroinitializer
; CHECK-NEXT:    store <4 x i1> [[IM_NARROW]], ptr [[P1]], align 1
; CHECK-NEXT:    store <4 x i1> [[FM_NARROW]], ptr [[P2]], align 1
; CHECK-NEXT:    ret void
;
; DISABLE-LABEL: define void @two_independent_chains(
; DISABLE-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x float> [[FA:%.*]], <4 x float> [[FB:%.*]], ptr [[P1:%.*]], ptr [[P2:%.*]], i1 [[C:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[ICMP1:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; DISABLE-NEXT:    [[FCMP1:%.*]] = fcmp olt <4 x float> [[FA]], [[FB]]
; DISABLE-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; DISABLE:       [[L]]:
; DISABLE-NEXT:    br label %[[J:.*]]
; DISABLE:       [[R]]:
; DISABLE-NEXT:    br label %[[J]]
; DISABLE:       [[J]]:
; DISABLE-NEXT:    [[IM:%.*]] = phi <4 x i1> [ [[ICMP1]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; DISABLE-NEXT:    [[FM:%.*]] = phi <4 x i1> [ [[FCMP1]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; DISABLE-NEXT:    store <4 x i1> [[IM]], ptr [[P1]], align 1
; DISABLE-NEXT:    store <4 x i1> [[FM]], ptr [[P2]], align 1
; DISABLE-NEXT:    ret void
;
  ptr %p1, ptr %p2, i1 %c) {
entry:
  %icmp1 = icmp eq <4 x i32> %a, %b
  %fcmp1 = fcmp olt <4 x float> %fa, %fb
  br i1 %c, label %l, label %r
l:
  br label %j
r:
  br label %j
j:
  %im = phi <4 x i1> [ %icmp1, %l ], [ zeroinitializer, %r ]
  %fm = phi <4 x i1> [ %fcmp1, %l ], [ zeroinitializer, %r ]
  store <4 x i1> %im, ptr %p1
  store <4 x i1> %fm, ptr %p2
  ret void
}

;-----------------------------------------------------------------------
; Non-chain non-constant operand consumed across non-dominating blocks
;-----------------------------------------------------------------------

;; A loaded <4 x i1> feeds two ANDs in non-dominating successor blocks
;; that join at a PHI. The widened sext of the load must be placed at the
;; load's def site (entry) so it dominates both consumers.
define <4 x i32> @nonchain_op_dominance(ptr %p, <4 x i32> %a, <4 x i32> %b,
; CHECK-LABEL: define <4 x i32> @nonchain_op_dominance(
; CHECK-SAME: ptr [[P:%.*]], <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], <4 x i32> [[Y:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X_I1:%.*]] = load <4 x i1>, ptr [[P]], align 1
; CHECK-NEXT:    [[TMP0:%.*]] = sext <4 x i1> [[X_I1]] to <4 x i32>
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[CMP_WIDE:%.*]] = sext <4 x i1> [[CMP]] to <4 x i32>
; CHECK-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; CHECK:       [[L]]:
; CHECK-NEXT:    [[ANDL_WIDE:%.*]] = and <4 x i32> [[CMP_WIDE]], [[TMP0]]
; CHECK-NEXT:    br label %[[J:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    [[ANDR_WIDE:%.*]] = and <4 x i32> [[CMP_WIDE]], [[TMP0]]
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[M_WIDE:%.*]] = phi <4 x i32> [ [[ANDL_WIDE]], %[[L]] ], [ [[ANDR_WIDE]], %[[R]] ]
; CHECK-NEXT:    [[M_NARROW:%.*]] = icmp slt <4 x i32> [[M_WIDE]], zeroinitializer
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M_NARROW]], <4 x i32> [[X]], <4 x i32> [[Y]]
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
; DISABLE-LABEL: define <4 x i32> @nonchain_op_dominance(
; DISABLE-SAME: ptr [[P:%.*]], <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], <4 x i32> [[Y:%.*]], i1 [[C:%.*]]) {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[X_I1:%.*]] = load <4 x i1>, ptr [[P]], align 1
; DISABLE-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; DISABLE-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; DISABLE:       [[L]]:
; DISABLE-NEXT:    [[ANDL:%.*]] = and <4 x i1> [[CMP]], [[X_I1]]
; DISABLE-NEXT:    br label %[[J:.*]]
; DISABLE:       [[R]]:
; DISABLE-NEXT:    [[ANDR:%.*]] = and <4 x i1> [[CMP]], [[X_I1]]
; DISABLE-NEXT:    br label %[[J]]
; DISABLE:       [[J]]:
; DISABLE-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[ANDL]], %[[L]] ], [ [[ANDR]], %[[R]] ]
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> [[Y]]
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
;
  <4 x i32> %x, <4 x i32> %y, i1 %c) {
entry:
  %x_i1 = load <4 x i1>, ptr %p, align 1
  %cmp = icmp eq <4 x i32> %a, %b
  br i1 %c, label %l, label %r
l:
  %andL = and <4 x i1> %cmp, %x_i1
  br label %j
r:
  %andR = and <4 x i1> %cmp, %x_i1
  br label %j
j:
  %m = phi <4 x i1> [ %andL, %l ], [ %andR, %r ]
  %sel = select <4 x i1> %m, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

;-----------------------------------------------------------------------
; Streaming-compatible SME: also skipped
;-----------------------------------------------------------------------

define <4 x i32> @sme_streaming_compat_skipped(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x, i1 %c) "aarch64_pstate_sm_compatible" {
; CHECK-LABEL: define <4 x i32> @sme_streaming_compat_skipped(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; CHECK:       [[L]]:
; CHECK-NEXT:    br label %[[J:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; CHECK-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
; DISABLE-LABEL: define <4 x i32> @sme_streaming_compat_skipped(
; DISABLE-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[X:%.*]], i1 [[C:%.*]]) #[[ATTR2:[0-9]+]] {
; DISABLE-NEXT:  [[ENTRY:.*:]]
; DISABLE-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; DISABLE-NEXT:    br i1 [[C]], label %[[L:.*]], label %[[R:.*]]
; DISABLE:       [[L]]:
; DISABLE-NEXT:    br label %[[J:.*]]
; DISABLE:       [[R]]:
; DISABLE-NEXT:    br label %[[J]]
; DISABLE:       [[J]]:
; DISABLE-NEXT:    [[M:%.*]] = phi <4 x i1> [ [[CMP]], %[[L]] ], [ zeroinitializer, %[[R]] ]
; DISABLE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M]], <4 x i32> [[X]], <4 x i32> zeroinitializer
; DISABLE-NEXT:    ret <4 x i32> [[SEL]]
;
entry:
  %cmp = icmp eq <4 x i32> %a, %b
  br i1 %c, label %l, label %r
l:
  br label %j
r:
  br label %j
j:
  %m = phi <4 x i1> [ %cmp, %l ], [ zeroinitializer, %r ]
  %sel = select <4 x i1> %m, <4 x i32> %x, <4 x i32> zeroinitializer
  ret <4 x i32> %sel
}
